import { StyleSheet, View } from "react-native"
import React from "react"
import { color } from "../../theme"

export const AuthStyles = StyleSheet.create({
  banner: {
    marginVertical: 16,
    alignItems: "center",
    flex: 1,
    height: 150,
    // maxHeight: 150,
    justifyContent: "center",
    backgroundColor: color.primary,
    borderRadius: 8,
  },
  avatar_banner: {
    marginVertical: 20,
    height: 80,
    width: 80,
    alignItems: "center",
    alignSelf: "center",
    flex: 1,
  },
  banner_img: {
    width: "100%",
    height: 120,
    resizeMode: "cover",
  },
  avatar_img: {
    width: 80,
    height: 80,
    resizeMode: "cover",
    borderRadius: 50,
    backgroundColor: "gray",
  },
  register_avatar_img: {
    width: 120,
    height: 120,
    resizeMode: "cover",
    borderRadius: 120,
    backgroundColor: "gray",
  },
  input: {
    width: "100%",
  },
  login_bottom_wrapper: {
    position: "absolute",
    bottom: 0,
    flex: 1,
    width: "100%",
    alignItems: "center",
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: 'white',
  },
  login_bottom_item: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  login_bottom_item_icon: {
    marginBottom: 6,
    // fontSize: 13,
    color: "#9098B1",
  },
  cccdImage_wrapper: {
    flex: 1, flexDirection: "row", justifyContent: "space-around", marginBottom: 10,
  },
  cccdImage_wrapper_button: {
    borderWidth: 1,
    borderColor: color.primary,
    borderRadius: 8,
    justifyContent: "center", alignItems: "center",
    // paddingHorizontal: 24,
    paddingVertical: 24,
    flex: 2,
    marginHorizontal: 8,
    backgroundColor:'white'
  },
  banner_swiper_item: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "gray",
    borderRadius: 8,
    marginHorizontal: 16,
  },
  cccdImage_wrapper_image: {
    minWidth: "100%",
    minHeight: "100%",
    resizeMode: "cover",
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1,
    borderRadius: 8,
  },
  cccdImage_wrapper_placeholder: {
    color: "#939AA4",
    fontSize: 12,
  },
  button: {
    // backgroundColor: "rgba(162, 50, 50, 1)",
    backgroundColor: color.primary,
    borderWidth: 0,
    height: 56,
    // width: "100%",
    alignItems: "center",
    borderRadius: 7,
    // fontSize: 30
  },
  button_sm: {
    backgroundColor: "#FFFFFF",
    borderColor: "#A23232",
    borderWidth: 1,
    width: "100%",
    alignItems: "center",
    borderRadius: 7,
  },
  button_icon: {
    alignSelf: "center",
    alignItems: "center",
    alignContent: "center",
    marginVertical: 20,
    width: 25,
    height: 25,
    resizeMode: "contain",
  },
  section: {
    alignItems: "center",
    marginTop: 30,
  },
  title: {
    fontSize: 13,
    alignSelf: "center",
    maxWidth: "80%",
  },
  title_txt: {
    // color: "#9098B1",
    textAlign: "center",
  },
  link_txt: {
    color: color.primary,
    fontSize: 13,
    fontWeight: "600",
    fontStyle: "italic",
    textDecorationLine: "underline",
  },
  gray_text: {
    fontSize: 13,
    color: "#9098B1",
  },
  input: {
    marginBottom: 10,
  },
  input_validate_txt: {
    color: "#A23232",
    marginBottom: 10,
    fontSize: 12,
    fontStyle: "italic",
  },
  input_otp: {
    borderWidth: 1,
    height: 42,
    // width: 35,
    padding: 2,
    textAlign: "center",
    borderRadius: 8,
    borderColor: color.primary,
  },
  input_otp_space: {
    flexDirection: "column",
    flex: 1,
    marginHorizontal: 7,
  },
  input_otp_space2: {
    flexDirection: "column",
    flex: 1,
    marginRight: 7,
    marginLeft: 2,
  },
  input_otp_space3: {
    flexDirection: "column",
    flex: 1,
    marginLeft: 7,
    marginRight: 2,
  },
  table_view: {
    flex: 1,
    height: "auto",
    paddingTop: 15,
  },
  row_view: {
    flexDirection: "row",
    marginVertical: 5,
  },
  col_view: {
    flex: 1,
    flexDirection: "column",
  },
  gray_label: {
    color: "#757577",
    fontSize: 13,
    fontWeight: "bold",
    alignContent: "center",
    height: 40,
    lineHeight: 40,
  },
  black_label: {
    color: "#000000",
    fontSize: 13,
    fontWeight: "bold",
    alignContent: "center",
    height: 40,
    lineHeight: 40,
  },
  col_left: {
    maxWidth: "25%",
  },
  news_cate_name: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#697077",
    textAlign: "center",
    marginTop: 8,
    textTransform: "uppercase",
  },
  news_item: {
    flexDirection: "column",
    height: 120,
    borderBottomWidth: 1,
    marginVertical: 5,
    paddingBottom: 10,
    borderColor: "#D6D8D8",
  },
  news_left_col: {
    flexDirection: "column",
    width: "45%",
  },
  news_right_col: {
    flexDirection: "column",
    width: "55%",
    paddingLeft: 10,
    position: "relative",
  },
  news_image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  news_title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#697077",
    textAlign: "center",
    marginTop: 8,
    textAlign: "left",
    lineHeight: 20,
  },
  news_item_cate: {
    position: "absolute",
    left: 5,
    bottom: 0,
    fontWeight: "bold",
    fontSize: 13,
    textTransform: "uppercase",
    color: "#A23232",
  },
  news_item: {
    flexDirection: "row",
    height: 120,
    borderBottomWidth: 1,
    marginVertical: 5,
    paddingBottom: 10,
    borderColor: "#D6D8D8",
  },
  news_left_col: {
    flexDirection: "column",
    width: "45%",
  },
  news_right_col: {
    flexDirection: "column",
    width: "55%",
    paddingLeft: 10,
    position: "relative",
  },
  news_image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  news_title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#697077",
    textAlign: "center",
    marginTop: 8,
    textAlign: "left",
    lineHeight: 20,
  },
  news_item_cate: {
    position: "absolute",
    left: 5,
    bottom: 0,
    fontWeight: "bold",
    fontSize: 13,
    textTransform: "uppercase",
    color: "#A23232",
  },
  cart_item: {
    flexDirection: "row",
    height: 120,
    borderBottomWidth: 1,
    marginVertical: 5,
    paddingBottom: 10,
    borderColor: "#D6D8D8",
  },
  cart_left_col: {
    flexDirection: "column",
    width: "25%",
  },
  cart_right_col: {
    flexDirection: "column",
    width: "75%",
    paddingLeft: 10,
    position: "relative",
  },
  cart_image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cart_title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#697077",
    textAlign: "center",
    marginTop: 8,
    textAlign: "left",
    lineHeight: 20,
  },
  cart_des: {
    fontSize: 14,
    color: "#697077",
    textAlign: "center",
    marginTop: 8,
    textAlign: "left",
    lineHeight: 20,
  },
  cart_price: {
    color: "#A23232",
  },
  cart_color: {
    width: 20,
    height: 20,
    borderRadius: 10,
    // lineHeight: 20,
  },
  cart_button: {
    backgroundColor: "#A23232",
    borderColor: "#A23232",
    position: "absolute",
    right: 0,
    bottom: 0,
    fontWeight: "bold",
    fontSize: 13,
    textTransform: "uppercase",
    color: "#A23232",
  },
  cart_category: {
    fontSize: 15,
    color: "#A23232",
    fontWeight: "bold",
    marginBottom: 15,
  },
  cart_on_img: {
    width: "100%",
    height: 180,
    resizeMode: "stretch",
    alignSelf: "center",
    borderRadius: 10,
  },
  cart_on_item: {
    flex: 1,
    marginHorizontal: 5,
    marginVertical: 5,
    height: 230,
    borderRadius: 10,
    marginBottom: 20,
  },
  cart_on_title: {
    marginVertical: 5,
    color: "#697077",
    fontSize: 14,
    fontWeight: "bold",
  },
  cart_on_cate: {
    color: "#991D1D",
    fontSize: 16,
    fontWeight: "bold",
  },
})
