export const images = {
  logo: require('./logo.png'),
  icon_notify: require('./Icon_notify.png'),
  icon_notify_2: require('./Icon_notify_2.png'),
  icon_menu:  require('./Icon_menu.png'),
  image_1:  require('./image_1.png'),
  image_2:  require('./image_2.png'),
  image_new:  require('./image_new.png'),
  images_about: require('./image_about.png'),
  icon_home: require('./icon_home.png'),
  image_tnm: require('./image_tnm.png'),
  person: require('./person.png'),
  location:require('./locationImage.png'),
  welcome:require('./Welcome.png'),
  icon_mess:require('./icon_mess.png'),
  iconSearch:require('./iconSearch.png'),
  JohnyTan:require('./JohnyTan.png'),
  iconHome:require('./IconHome.png'),
  iconBack: require('./IconBack.png'),
  icon_level: require('./icon_level.png'),
  icon_type: require('./icon_type.png'),
  icon_edu: require('./icon_edu.png'),
  icon_exp: require('./icon_exp.png'),
  icon_category: require('./icon_category.png'),
  icon_industry: require('./icon_industry.png'),
  icon_share: require('./icon_share.png'),
  icon_upload: require('./icon_upload.png'),
  icon_location: require('./icon_location.png'),
  icon_phone: require('./icon_phone.png'),
  icon_email: require('./icon_email.png'),
  icon_position: require('./icon_position.png'),
  iconHappy:require('./iconHappy.png'),
  iconGhim:require('./iconGhim.png'),
  iconEnter: require('./iconEnter.png'),
  image_thanks: require('./image_thanks.png'),
  iconFacebook:require('./iconFacebook.png'),
  iconIn:require('./iconIn.png'),
  modal_thank_you:require('./modal_thank_you.png'),
  iconGmail:require('./iconGmail.png'),
  iconPW:require('./iconPW.png'),
  iconEyePW:require('./iconEyePW.png'),
  BGLoginLeft:require('./BGLoginLeft.png'),
  BGLoginRight:require('./BGLoginRight.png'),
  imageForgotPW:require('./imageForgotPW.png'),
  iconBackPW:require('./iconBackPW.png'),
  imagePW:require('./imagePW.png'),
  imagePWChange:require('./imagePWChange.png'),
  logoRegister:require('./logo_register.png')
};
